### ISSUE TITLE
Yarn install failing on step "Generating type definitions with tsc"

### ISSUE THREAD

**Issue by lklepner** [react-native-community/bob#22]
# Bug

Hi! Our react native project has begun throwing typescript errors from within the bob builds during yarn install. 

Studying our last successful build log we see it used `tsc version 3.7.5` and our failing builds are using `tsc version 3.8.2`. 

Is there a way to pin the version of `tsc` used by bob? 

We have tried listing typescript as a devDependency in our package.json but the log output shows its continuing to use 3.8.2. 

Any advice here would be greatly appreciated! 

```
...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
$ bob build
ℹ Building target commonjs
ℹ Cleaning up previous build at lib/commonjs
ℹ Compiling 10 files in src with babel
✓ Wrote files to lib/commonjs
ℹ Building target module
ℹ Cleaning up previous build at lib/module
ℹ Compiling 10 files in src with babel
✓ Wrote files to lib/module
ℹ Building target typescript
ℹ Cleaning up previous build at lib/typescript
ℹ Generating type definitions with tsc
✖ Errors found when building definition files.
Version 3.8.2
Syntax:   tsc [options] [file...]

Examples: tsc hello.ts
          tsc --outFile file.js file.ts
          tsc @args.txt
          tsc --build tsconfig.json

[... trimming out the rest of the tsc man file ...]

Error: Failed to build definition files.
    at build (/Users/ciuser/Library/Caches/Yarn/v6/.tmp/ea51ffe15838536cf328cbec1d27f294.3131f0e74df9ee1ee28c4fcebd18b055b4fac308.prepare/node_modules/@react-native-community/bob/lib/targets/typescript.js:63:11)
```

## Environment info

React native info output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 3.62 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/opt/node@10/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.0, 25.0.1, 26.0.1, 26.0.2, 27.0.0, 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
```

Library version: x.x.x

## Steps To Reproduce

1.  yarn install
2. bob build error reported
...

Describe what you expected to happen:

1. successful yarn install

**Comment by satya164** [comment]
It should use the typescript from your devDependencies if you have one. Can you share a repro that I can check?

**Comment by lklepner** [comment]
It turns out we had dependencies which didn't have a version of typescript defined. After pinning these dependencies to an older version of typescript things began building again. Finding the problem dependencies was a challenge though.. I wonder if the error surfaced from bob could provide some details on which code caused the error?

**Comment by satya164** [comment]
Bob just prints whatever error typescript shows without removing anything. You'd get the same error if you run tsc manually.

Closing since this is not a bob specific issue.

**Comment by lklepner** [comment]
Ahh, that makes sense. Thanks for the feedback and quick responses!
