### ISSUE TITLE
Build module (Add storybook)

### ISSUE THREAD

**Issue by TfADrama** [react-native-community/bob#36]
# Question

I there! I created a module with the following command:
`npx @react-native-community/bob create react-native-awesome-module`

I want to create a lib/module of components and i need to have [storybook](https://storybook.js.org/docs/guides/guide-react-native/) on it. 
But i need to execute the lib in order to use storybook, but the lib isn't executable. 

**It is possible to make the lib able to run in order to use Storybook or other available libs?**

**Comment by satya164** [comment]
Run the example app. Look at the CONTRIBUTING.md that's generated in the project.
