### ISSUE TITLE
How to include assets in package?

### ISSUE THREAD

**Issue by RajanPalaniya** [react-native-community/bob#42]
# Question

Hi There,

I have a question regarding this to using this cli that, how can i include any assets for my component package?

eg. images, fonts, json files etc..

as for in the code i have defined absolute path to resolve the images and json files also i have the gradle file and podspec file to include fonts in parent application.

My package is written in typescript.

How can i include all of these assets in my final package?

**Comment by satya164** [comment]
If you have them in a separate folder, put that folder in `files` field in `package.json`. If it's under `src`, it'll already be included.

**Comment by YOEL311** [comment]
@satya164 
if it exists under the src  folder
It will copy it to both folders for me
Is it worth it?
Now everyone will get it twice?
