### ISSUE TITLE
Example slug broken inside example app in app.json

### ISSUE THREAD

**Issue by peterpme** [react-native-community/bob#49]
# Bug report

- I'm using the latest version of Bob

Hi!

This project is awesome! One thing I've noticed is that when generating a new project name like : `@draftbit/modules` the example app slug is also: `@draftbit/modules` which throws an error when running `yarn start`.

I'm not sure if this is just a me problem, but perhaps its worth stripping the `@` and `/` in slug for generating app.json

## Steps to reproduce:

- generate a new project and call it `@draftbit/whatever` or any namespaced module
- `cd example && yarn && yarn start`

## Expectation

No error message

Thank you

**Comment by satya164** [comment]
I think we're always appending `-example` in example's name:

https://github.com/react-native-community/bob/blob/e586050802ac517418ab6c47bef2094b6c047ab0/templates/native-library/example/%24package.json#L2
https://github.com/react-native-community/bob/blob/e586050802ac517418ab6c47bef2094b6c047ab0/templates/expo-library/example/%24package.json#L2

I also tried initing a new project with the name `@draftbit/modules`, but it seems to run fine for me and the example has `-example` at end of its name. Can you mention the options you selected when creating the module?

I found another issue that the slug for expo app is invalid in `app.json` but it seems to be a different issue and only logs an error in terminal.

**Comment by peterpme** [comment]
Hey, sorry about the delay. Got lost in my email. I think it has to do with example/app.json's `slug` when running `expo start`

**Comment by satya164** [comment]
Should be fixed in https://github.com/react-native-community/bob/commit/ffc6e18fc0f5a0ab382a1ed698fed90c4ce3ae08
