### ISSUE TITLE
Example project mismatch React-native version from the Bridge

### ISSUE THREAD

**Issue by ebellumat** [react-native-community/bob#52]
Package.JSON of the library genereted.

```
  "devDependencies": {
    "react": "~16.9.0",
    "react-native": "~0.61.5",
  },
```

Package.JSON from the example project.

```
  "dependencies": {
    "react": "16.11.0",
    "react-native": "0.62.0"
  },

````

Because of this, the example project doesn't run.

![image](https://user-images.githubusercontent.com/26942680/83177501-8d85a880-a0f5-11ea-85b5-2dfee80ad487.png)

**Comment by ebellumat** [comment]
To run, i have to use https://react-native-community.github.io/upgrade-helper/ comparing the version 0.61.5 to 0.62.0 and downgrade all the files of example project, annoying, but work.

**Comment by satya164** [comment]
We need to fix it, but why didn't you just bump the versions in root package.json instead of downgrading the whole example project?

**Comment by AmalMenachery** [comment]
@satya164 The packages added in the root project needs to be reflected in the example project realtime right ? while installing new packages, the modules are not being resolved in the example project, but it works fine if used after packing and install the library in another project.

**Comment by satya164** [comment]
@AmalMenachery they should work fine, except the ones in peer deps which you need to install under example too. can you share a repro?

**Comment by satya164** [comment]
https://github.com/react-native-community/bob/commit/474c748e1a49e261ce4203d5b16a359bd4d76f7f
