### ISSUE TITLE
file names error by creating module on Windows

### ISSUE THREAD

**Issue by b3coded** [react-native-community/bob#53]
# Bug report

## Summary

I'm using Windows to create a native module but some files have incorrect names.

## Environment info

`react-native info` output:

```bash
  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 6.62 GB / 11.88 GB
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 25.0.0, 25.0.1, 27.0.3, 28.0.3, 29.0.2
      System Images: android-R | Google Play Intel x86 Atom
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-native: ~0.61.5 => 0.61.5
```

Library version: 0.14.5

## Steps to reproduce

1.  `npx @react-native-community/bob create rn-test-module`
2. `cd rn-test-module`
3.  `yarn bootstrap`

Describe what you expected to happen:

1. Create the project
2. All the name of files matching with library name

## Reproducible sample code

![image](https://user-images.githubusercontent.com/38642628/83351502-f26e1800-a31a-11ea-98b5-94ce440a86f5.png)

**Comment by AmalMenachery** [comment]
%= project.name % This is not resolved, which ends up in error
