### ISSUE TITLE
Using swift to build native modules

### ISSUE THREAD

**Issue by TfADrama** [react-native-community/bob#54]
# Question
I'm trying to use swift files on the library.

I created a swift file in order to get xcode to create a bridge file for me, it didn't happen. So i created a bridge file MyClass-Bridging-Header.h with only:

`#import "React/RCTBridgeModule.h"`

Then, i added the name of the file here:
`SWIFT_OBJC_BRIDGING_HEADER = MyClass-Bridging-Header.h`

On the swift file i added the following code:
```import Foundation
@objc(MyClass)

class MyClass: NSObject {
    @objc
    override static func requiresMainQueueSetup() -> Bool {
        return false
    }
    @objc func testFn() {
        print("This is a test function")
    }
}
```

Then i deleted the .h file automatically created by the lib. And in the -m file i deleted everything inside and added this:

```
#import "React/RCTBridgeModule.h"
@interface RCT_EXTERN_MODULE(MyClass, NSObject)
@end
```

After this i confirmed that the example project has a bridging header for swift files.

Then i tried to compile the example project and an error appears:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MyClass", referenced from:
      objc-class-ref in libreact-native-swift-test.a(MyClass.o)
      __OBJC_$_CATEGORY_MyClass_$_RCTExternModule in libreact-native-swift-test.a(MyClass.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It is possible to have native modules using swift?

**Comment by Neck1T** [comment]
Try to add **swift** in podspec

_s.source_files = "ios/**/*.{h,m,mm,**swift**}"_
