### ISSUE TITLE
How can I create javascript modules (no native dependency) using React Native CLI rather than Expo?

### ISSUE THREAD

**Issue by rashtay** [react-native-community/bob#61]
# Question

I am using the below-listed dependencies:
```
    "@react-native-community/async-storage": "*",
    "react": "*",
    "react-native": "*",
    "react-native-extended-stylesheet": "*",
    "react-native-fast-image": "*",
    "react-native-localization": "*",
    "react-native-safe-area-context": "*",
    "react-native-vector-icons": "*"
```
 to export reusable components. It is very similar to `react-native-paper`. I just want to install the package and start using it rather than running `npx pod-install`.

The problem with choosing `Javascript modules with native example` is, it uses Expo. I do not want to use expo. Instead, I want to use React Native CLI for examples so that I can integrate `react-native-vector-icons`

This package is brilliant and I have already built a package by choosing the option `Kotlin and Swift` which offers exactly what I need, but I had to run `npx pod-install` in my actual project to connect my `npm package` which seems pointless for exporting non-native modules. For example, let's say I created `react-native-components` and installed in my project like so `npm install react-native-components`. Then, I had to run `npx pod-install`. But, I am sure it happened because I chose `Native module with Kotlin and swift`.

How can I create component, render the components in an example react-native cli application by linking the package and connect the packages with the native dependencies such as `react-native-vector-icons` directly in the example project?

Any help is appreciated.

**Comment by satya164** [comment]
> The problem with choosing Javascript modules with native example is, it uses Expo

Looks like a typo. Should be fixed in latest version.

> This package is brilliant and I have already built a package by choosing the option Kotlin and Swift which offers exactly what I need, but I had to run npx pod-install in my actual project to connect my npm package which seems pointless for exporting non-native modules.

If you chose Kotlin and Swift then it's not non-native, you're including native code.

**Comment by rashtay** [comment]
@satya164 That is true, but there aren't any other options I can choose to work with an example project without expo. By your reply I am assuming, the next version would have an example set up using react-native cli rather than an expo set up

**Comment by rashtay** [comment]
Hey @satya164 

It has been fixed. Thank you so much. This is very useful
