### ISSUE TITLE
Adding Packages to Library and using them in Base Application

### ISSUE THREAD

**Issue by AmalMenachery** [react-native-community/bob#71]
# Question :
We are currently using the [mapbox-gl](https://github.com/react-native-mapbox-gl/maps), for a component. We are customizing the component as required and export our component in index. For the example App for make it work, we have added the mapbox-gl package in example project too. Is it required to add the mapbox-gl package in the Application where we  install our library ,since the mapbox-gl is mentioned in the library dependencies ? This should be automatically installed while we installed the library right ?

**Comment by AmalMenachery** [comment]
@satya164 FYI

**Comment by Krizzu** [comment]
duplicate https://github.com/react-native-community/bob/issues/89
