### ISSUE TITLE
Use CocoaPods dependency in native module library

### ISSUE THREAD

**Issue by amoghpalnitkar** [react-native-community/bob#72]
What is the best way to include a CocoaPods library inside my native module? 
Has anyone managed to get it working?

Any insights appreciated.

Cheers,
Amogh

**Comment by Krizzu** [comment]
Can you elaborate more what you mean? [Bob already creates a podspec for your module](https://github.com/react-native-community/bob/blob/master/templates/native-library/%7B%25%3D%20project.podspec%20%25%7D.podspec)

**Comment by amoghpalnitkar** [comment]
Apologies if I was unclear earlier. 

Some more context :-

I would like to use a library which is hosted as cocoapod inside my ios native-module.

For example:
say I want to include `pod 'AFNetworking' ` inside my native module, to be able to use AFNetworking functions inside my module, how do I go about doing it?

Does this make thing clearer?

**Comment by amoghpalnitkar** [comment]
I believe `pod init` inside the library is working just fine.

Closing this.
