### ISSUE TITLE
.babelrc config files should be merged with top-level config

### ISSUE THREAD

**Issue by jsamr** [react-native-community/bob#80]
# Bug report

## Summary

`.babelrc` files are not merged with compiled configurations. Technically, there is no such thing as a top-level config, since the configuration is generated by the compile function. But to match closely the semantics of babel v7, I believe it would be best to merge the configuration. See [File Relative Configuration](https://babeljs.io/docs/en/config-files#file-relative-configuration):

> File-relative configurations are also merged over top of project-wide config values, making them potentially useful for specific overrides.

Note: I can provide a reproduction if required.

**Comment by satya164** [comment]
You can acheive it with `babelrc: true` and `configFile: true` options: https://github.com/react-native-community/bob#commonjs

**Comment by jsamr** [comment]
@safaiyeh I am well aware there is a babelrc option. The semantics of .babelrc files have changed with babel 7, hence the quote in my message. In the current implementation, if you add your own babelrc file, the original configuration object created by bob is lost. Thus there is no merging. My use case is: I want to add a babel plugin (inline imports). Perhaps another solution would be to be able to explicitly declare babel plugin configurations in the bob entry.

So to be clear, this is why I need to do to achieve my goal today with bob:

```jsonc
// .babelrc
{
  "presets": ["@babel/typescript", "@babel/env", "@babel/react", "@babel/flow"],
  "plugins": [
    [
      "babel-plugin-inline-import",
      {
        "extensions": ["webjs"]
      }
    ],
    "@babel/plugin-proposal-class-properties"
  ]
}
```
Now, if .babelrc files are merged with the generated config object, I would only need this to achieve the same goal:
```jsonc
// .babelrc
{
  "plugins": [
    [
      "babel-plugin-inline-import",
      {
        "extensions": ["webjs"]
      }
    ]
  ]
}
```
That would closer match babel documentation which states:
> File-relative configurations (.babelrc) are also merged over top of project-wide config values, making them potentially useful for specific overrides. Basically, the config object generated by bob would act as the "project-wide config value".

**Comment by safaiyeh** [comment]
Tagged the wrong person 😂 cc @satya164

**Comment by jsamr** [comment]
@safaiyeh Oops sorry ^^ I gave too much trust on github autosuggestions I guess, you were the first match :laughing:

**Comment by joker-777** [comment]
@satya164 Any feedback about this issue? Using a custom configuration makes it impossible to compile it for commonjs and module. You have to one of them.
