### ISSUE TITLE
can I specify a tsconfig.json file to build, not the default one in root directory?

### ISSUE THREAD

**Issue by chj-damon** [react-native-community/bob#84]
# Feature request

## Why it is needed
in my project tsconfig.json file, I set `noEmit`: true, but when build library, I have to set `noEmit`: false to generate type definition files.
`bob build` cannot accept any parameters in command or specify a tsconfig.json file.

## Possible implementation
`bob build --file tsconfig.build.json`
or
`bod build --noEmit false --emitDeclarationOnly true`

**Comment by Krizzu** [comment]
You can have [two typescript config](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#tsconfig-bases), where one of them is extension with `noEmit` set to false. Then let [bob know which config to use](https://github.com/react-native-community/bob#typescript)

**Comment by chj-damon** [comment]
Thanks, sorry for bothering you. I should've read the document more carefully.
