### ISSUE TITLE
How can I use another package with my react-native component module

### ISSUE THREAD

**Issue by onurcskun** [react-native-community/bob#91]
Hi,

For a couple of days, I am struggling with this problem. 

My plan is creating a component module that opens webview (comunity/react-native-webview) inside a modal.
- I created a library using bob and selected "javascript module with native example".
- Then I installed react-native-webview and used it.
```javascript
import React from 'react';
import { View, Modal } from 'react-native';
import WebView from 'react-native-webview';

const App: React.FC<{}> = () => {
  return (
    <Modal>
      <View style={{
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
      }}>
        <WebView source={{ uri: 'https://github.com'}} />
      </View>
    </Modal>
  )
};

export default App;
```
in index.js
```javascript
import React from 'react';
import App from './App';

export default {
  multiply(a: number, b: number) {
    return Promise.resolve(a * b);
  },
  widget() {
    return <App />;
  }
};
```
- I did bob build

- And in the example project, I reinstalled my module and use it.
```javascript
import * as React from 'react';
import { StyleSheet, View, Text } from 'react-native';
import RnWidget from 'rn-widget';

export default function App() {
  const [result, setResult] = React.useState();

  React.useEffect(() => {
    RnWidget.multiply(3, 7).then(setResult);
  }, []);

  return (
    <View style={styles.container}>
      <Text>Result: {result}</Text>
      {RnWidget.widget()}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

- executed run ios and the output is

![image](https://user-images.githubusercontent.com/20303109/94127280-69e32c80-fe61-11ea-88e9-1d049b3453c0.png)

if I don't use webview its okay, I can display everything in react-native; but if I use another package I am getting this issue

**Comment by onurcskun** [comment]
I found that nothing supports symlinks. So you can work with only the example folder in the library.

**Comment by chenweigh** [comment]
> I found that nothing supports symlinks. So you can work with only the example folder in the library.

How to fix it? The same problem to e
