### ISSUE TITLE
React native linking

### ISSUE THREAD

**Issue by sidhanshumonga** [react-native-community/bob#94]
# Question

I am facing an issue in linking some dependency which is required in package I am creating. For example, Async storage is required for my new package but where I am installing my package, doesn't have Async storage. How can I achieve this?

**Comment by Vluf** [comment]
Facing this same issue, adding AsyncStorage to the module crashes the example app because it does not autolink.

**Comment by sidhanshumonga** [comment]
I got the solution for this. When you install your package to example app, you need to install AsyncStorage through npm install. It fails to autolink because it is present in node_modules but does not present in package.json. So, by doing `npm install 'AsyncStoragePackageName'` it will be fixed.

**Comment by Vluf** [comment]
Adding AsyncStorage to your `package.json` is not feasible if your module has multiple dependencies IMO. You'd have to request your library user to install all your dependencies .
I set up a small test app (outside of the module directory) that installs the module through NPM, but this also fails to link up AsyncStorage :/

**Comment by Vluf** [comment]
Related: https://github.com/facebook/react-native/issues/28838

**Comment by chj-damon** [comment]
I'm facing the same problem now.

**Comment by satya164** [comment]
https://github.com/callstack/react-native-builder-bob#how-do-i-add-a-react-native-library-containing-native-code-as-a-dependency-in-my-library

**Comment by drpym** [comment]
I am facing the same problem now, with the same package. I was able to have it install as a peer dependency. Which installs fine. However I still have to add a line the Podfile of the app to RNCAsyncStorage :path `/blah` so that it works.

Has anyone been able to auto link peer dependencies?

**Comment by tushar04** [comment]
> I am facing the same problem now, with the same package. I was able to have it install as a peer dependency. Which installs fine. However I still have to add a line the Podfile of the app to RNCAsyncStorage :path `/blah` so that it works.
> 
> Has anyone been able to auto link peer dependencies?

Have you resolved this issue @golden-protocol. Im facing the issue.
